# Generated by Django 5.2.11 on 2026-02-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL товара')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('threshold_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная пороговая цена')),
                ('threshold_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная пороговая цена')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая цена')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ['-created_at'],
            },
        ),
    ]
