# Generated by Django 5.2.11 on 2026-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная пороговая цена', max_digits=10, null=True, verbose_name='Макс. порог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='threshold_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная пороговая цена', max_digits=10, null=True, verbose_name='Мин. порог'),
        ),
    ]
