# Generated by Django 5.2.11 on 2026-02-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_product_name_alter_product_threshold_price_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Последняя цена'),
        ),
    ]
